<!-- This code was generated by Builder.io -->
<template>
  <main class="main-container">
    <section class="image-wrapper">
      <a href="https://www.figma.com/community/search?resource_type=mixed&sort_by=relevancy&query=landing+page&editor_type=all&price=free&creators=all"
        target="_blank" class="link">Browse free designs</a>
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F057741175755416385a1000c5f69003a%2F88269fc60fc14fcbb1683481d3034bcc"
        class="img" />
      <div class="shop-link">
        <a href="#" class="link">Shop</a>
      </div>
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e156506-f480-41cc-a004-55fa95d9198b?apiKey=057741175755416385a1000c5f69003a&"
        class="img-2" />
      <div class="learn-link">
        <a href="#" class="link">Learn</a>
      </div>
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4ab262d4-b1bd-46a5-91a0-83944cfc771b?apiKey=057741175755416385a1000c5f69003a&"
        class="img-3" />
    </section>
    <section class="get-started-container">
      <div class="get-started-wrapper">
        <div class="get-started">
          <a href="#" class="link">Get Started</a>
        </div>
        <img loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4a93bdb3-6bc3-4dbb-b5fa-ad5a3bddeb17?apiKey=057741175755416385a1000c5f69003a&"
          class="img-4" />
      </div>
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/26ff4355-2849-49a6-a8e3-285428610071?apiKey=057741175755416385a1000c5f69003a&"
        class="img-5" />
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c022eb3a-4d4a-4f11-b3ca-5471b2030730?apiKey=057741175755416385a1000c5f69003a&"
        class="img-6" />
    </section>
    <section class="description-container">
      <h2 class="title">Press play <br />on our headphones</h2>
      <p class="description">
        Now available in Halloween <br />Limited Editions
      </p>
      <div class="get-started-wrapper">
        <div class="get-started">
          <a href="#" class="link">Get Started</a>
        </div>
        <img loading="lazy" srcSet="..." class="img-7" />
      </div>
    </section>
  </main>
</template>

<script>
export default {
  name: "my-component_hero",
};
</script>

<style scoped>
.main-container {
  background-color: #aaaaaa;
  display: flex;
  flex-direction: column;
}

.image-wrapper {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  align-self: stretch;
  position: relative;
  display: flex;
  min-height: 1024px;
  width: 100%;
  padding: 40px 20px;
}

@media (max-width: 991px) {
  .image-wrapper {
    max-width: 100%;
  }
}

.img {
  position: absolute;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.shop-link,
.learn-link {
  justify-content: center;
  color: #fff;
  text-align: center;
  font-family: Trebuchet MS, sans-serif;
  font-size: 15px;
  font-weight: 700;
  line-height: 160%;
  letter-spacing: 0.3px;
  text-transform: uppercase;
  align-self: stretch;
}

.img-2,
.img-3 {
  aspect-ratio: 1.6;
  object-fit: cover;
  object-position: center;
  width: 8px;
  fill: #fff;
  overflow: hidden;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
}

.get-started-container {
  align-self: stretch;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 15px;
}

@media (max-width: 991px) {
  .get-started-container {
    justify-content: center;
  }
}

.get-started-wrapper {
  border-radius: 8px;
  background-color: #fff;
  align-self: start;
  display: flex;
  width: 154px;
  max-width: 100%;
  padding: 11px 12px 11px 17px;
  align-items: flex-start;
  gap: 10px;
}

.get-started {
  justify-content: center;
  color: #232323;
  font-family: Trebuchet MS, sans-serif;
  font-size: 15px;
  font-weight: 700;
  line-height: 134%;
  letter-spacing: 0.3px;
  text-transform: uppercase;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
}

.img-4 {
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 18px;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}

.img-5,
.img-6 {
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 38px;
  fill: #fff;
  overflow: hidden;
  align-self: start;
  margin-top: 2px;
}

.description-container {
  align-self: start;
  display: flex;
  margin-top: 225px;
  width: 473px;
  max-width: 100%;
  flex-grow: 1;
  flex-direction: column;
}

@media (max-width: 991px) {
  .description-container {
    margin-top: 200px;
  }
}

.title {
  justify-content: center;
  color: #fff;
  font-family: Georgia, sans-serif;
  font-size: 74.923px;
  font-weight: 700;
  line-height: 109%;
  letter-spacing: 0.749px;
  align-self: start;
}

@media (max-width: 991px) {
  .title {
    max-width: 100%;
    font-size: 40px;
  }
}

.description {
  justify-content: center;
  color: #fff;
  font-family: Trebuchet MS, sans-serif;
  font-size: 27.606px;
  font-weight: 700;
  line-height: 156%;
  letter-spacing: 0.552px;
  align-self: start;
  margin-top: 25px;
}

.get-started-wrapper {
  border-radius: 16.146px;
  background-color: #ff6134;
  align-self: start;
  display: flex;
  margin-top: 71px;
  width: 258px;
  max-width: 100%;
  flex-grow: 1;
  padding: 33px 20px;
  flex-direction: column;
}

.get-started-wrapper .get-started {
  align-self: start;
  display: flex;
  margin-top: 1px;
  margin-left: 20px;
  margin-bottom: -2px;
  width: 193px;
  max-width: 100%;
  align-items: flex-start;
  gap: 19px;
}

@media (max-width: 991px) {
  .get-started-wrapper .get-started {
    margin-left: 10px;
  }
}

.get-started-wrapper .get-started .link {
  justify-content: center;
  color: #fff;
  font-family: Trebuchet MS, sans-serif;
  font-size: 23.005px;
  font-weight: 700;
  line-height: 134%;
  letter-spacing: 0.46px;
  text-transform: uppercase;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
  width: 162px;
}

.img-7 {
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 25px;
  fill: #ffa51e;
  overflow: hidden;
}
</style>
